apps/core/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import (index,requisicao_view,requisicao_add,auth_view,csv_add,
					beneficiarias, secretarias, beneficiaria_view)

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^beneficiarias$', beneficiarias, name='beneficiarias'),
    url(r'^secretarias$', secretarias, name='secretarias'),
    url(r'^beneficiarias/view/(?P<pk>[0-9]+)/$', beneficiaria_view, name='beneficiaria-view'),
    url(r'^requisicao/add/$', requisicao_add, name='requisicao-add'),
    url(r'^requisicao/(?P<pessoa>[F|J]+)/(?P<pk>[0-9]+)/$', requisicao_view, name='requisicao-view'),
    url(r'^autorizacao/(?P<pk>[0-9]+)/$', auth_view, name='auth-view'),
    url(r'^itens/add/$', csv_add, name='csv-add'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

srp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.core import urls as core_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(core_urls, namespace='core')),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<title>{% block title %}{% endblock %} | SRP</title>
    <link href="https://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" media="screen">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" />
	<link rel="stylesheet" href="{% static 'vendors/tags/css/bootstrap-tags.css' %}" />
	<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
	<link rel="stylesheet" href="{% static 'vendors/datatables/dataTables.bootstrap.css' %}" />
	<link rel="stylesheet" href="{% static 'vendors/bootstrap-datetimepicker/datetimepicker.css' %}" />

</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">

{% include "nav.html" %}
<div class="page-content">
	<div class="row">
		{% include "side_menu.html" %}
		<div class="col-md-10">
			<div class="row">
			{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</div>
<script src="{% static 'js/jquery.js' %}"></script> 
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script> 
<script src="{% static 'vendors/datatables/js/jquery.dataTables.min.js' %}"></script> 
<script src="{% static 'vendors/select/bootstrap-select.min.js' %}"></script> 
<script src="{% static 'vendors/tags/js/bootstrap-tags.min.js' %}"></script> 
<script src="{% static 'vendors/datatables/dataTables.bootstrap.js' %}"></script> 
<script src="{% static 'js/tables.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/forms.js' %}"></script>
<script type="text/javascript">
  $('tr[data-href]').on("click", function() {
      document.location = $(this).data('href');
  });
</script>
<script type="text/javascript">
$('{{erro}}').modal('show');
</script>
</body>
</html>

templates/nav.html
<div class="header">
   <div class="container">
      <div class="row">
         <div class="col-md-5">
            <!-- Logo -->
            <div class="logo">
               <h1><a href="index.html">Sistema SRP</a></h1>
            </div>
         </div>
         <div class="col-md-5">
            <div class="row">
              <div class="col-lg-12">
                <div class="input-group form">
                     <input type="text" class="form-control" placeholder="Search...">
                     <span class="input-group-btn">
                       <button class="btn btn-primary" type="button">Search</button>
                     </span>
                </div>
              </div>
            </div>
         </div>
         <div class="col-md-2">
            <div class="navbar navbar-inverse" role="banner">
                <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                  <ul class="nav navbar-nav">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                      <ul class="dropdown-menu animated fadeInUp">
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="login.html">Logout</a></li>
                      </ul>
                    </li>
                  </ul>
                </nav>
            </div>
         </div>
      </div>
   </div>
</div>

templates/side_menu.html
<div class="col-md-2">
	<div class="sidebar content-box" style="display: block;">
		<ul class="nav">
			<!-- Main menu -->
			<li class="current"><a href="{% url 'core:index'%}"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
			<li class="current"><a href="{% url 'core:secretarias'%}"><i class="glyphicon glyphicon-book"></i> Secretarias</a></li>
			<li class="submenu">
				<a href="#">
					<i class="glyphicon glyphicon-list"></i> Beneficiárias
					<span class="caret pull-right"></span>
				</a>
				
				<ul>
					<li><a href="{% url 'core:beneficiarias'%}"><i class="glyphicon glyphicon-calendar"></i> Beneficiárias</a></li>
					<li><a href="signup.html"><i class="glyphicon glyphicon-user"></i> Representantes</a></li>
				</ul>
			</li>
<!-- 			<li><a href="stats.html"><i class="glyphicon glyphicon-stats"></i> Statistics (Charts)</a></li>
			<li><a href="tables.html"><i class="glyphicon glyphicon-list"></i> Tables</a></li>
			<li><a href="buttons.html"><i class="glyphicon glyphicon-record"></i> Buttons</a></li>
			<li><a href="editors.html"><i class="glyphicon glyphicon-pencil"></i> Editors</a></li>
			<li><a href="forms.html"><i class="glyphicon glyphicon-tasks"></i> Forms</a></li>
			<li class="submenu">
				<a href="#">
					<i class="glyphicon glyphicon-list"></i> Pages
					<span class="caret pull-right"></span>
				</a>
			
				<ul>
					<li><a href="login.html">Login</a></li>
					<li><a href="signup.html">Signup</a></li>
				</ul>
			</li> -->
		</ul>
	</div>
</div>