apps/core/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import (index,requisicao_view,requisicao_add,auth_view,csv_add,
					beneficiarias, secretarias, beneficiaria_view)

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^beneficiarias$', beneficiarias, name='beneficiarias'),
    url(r'^secretarias$', secretarias, name='secretarias'),
    url(r'^beneficiarias/view/(?P<pk>[0-9]+)/$', beneficiaria_view, name='beneficiaria-view'),
    url(r'^requisicao/add/$', requisicao_add, name='requisicao-add'),
    url(r'^requisicao/(?P<pessoa>[F|J]+)/(?P<pk>[0-9]+)/$', requisicao_view, name='requisicao-view'),
    url(r'^autorizacao/(?P<pk>[0-9]+)/$', auth_view, name='auth-view'),
    url(r'^itens/add/$', csv_add, name='csv-add'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

srp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.core import urls as core_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(core_urls, namespace='core')),
]

apps/core/forms.py
from django import forms
from .models import Requisicao, ReqItem
from django.forms.extras.widgets    import SelectDateWidget
from django.forms.formsets import formset_factory, BaseFormSet


class RequisicaoForm(forms.ModelForm):
    class Meta:
        model = Requisicao
        fields = [
            'fk_pregao','secretaria','ano','n_proc','data_pro',
            'assinatura','requisicao','ed','pa','meta','acao',
            'fonte','aut','justificativa','contrato','empenho','vigencia','objeto',
        ]
        widgets = {
            'fk_pregao' : forms.Select(attrs={
                'placeholder':'Pregão',
                'class':'form-control',
            }),
            'secretaria' : forms.Select(attrs={
                'placeholder':'Secretaria',
                'class':'form-control',
            }),
            'ano' : forms.Select(attrs={
                'placeholder':'Ano',
                'class':'form-control',
            }),
            'n_proc' : forms.NumberInput(attrs={
                'placeholder':'Nº do Processo',
                'class':'form-control',
            }),
            'data_pro' : forms.DateInput(attrs={
                'placeholder':'Data do Processo',
                'class':'form-control',
            }),
            'vigencia' : forms.DateInput(attrs={
                'placeholder':'Data de Encerramento',
                'class':'form-control',
            }),
            'assinatura' : forms.DateInput(attrs={
                'placeholder':'Assinatura',
                'class':'form-control',
            }),
            'requisicao' : forms.NumberInput(attrs={
                'placeholder':'Nº da Requisicao',
                'class':'form-control',
            }),
            'pa' : forms.NumberInput(attrs={
                'placeholder':'Projeto/Atividade',
                'class':'form-control',
            }),
            'ed' : forms.TextInput(attrs={
                'placeholder':'Elemento de Despesa',
                'class':'form-control',
                'data-inputmask':"'mask': '9.9.99.99.99'",
            }),
            'meta' : forms.NumberInput(attrs={
                'placeholder':'Meta',
                'class':'form-control',
            }),
            'acao' : forms.NumberInput(attrs={
                'placeholder':'Ação',
                'class':'form-control',
            }),
            'fonte' : forms.NumberInput(attrs={
                'placeholder':'Fonte',
                'class':'form-control',
            }),
            'aut' : forms.NumberInput(attrs={
                'placeholder':'Autorização',
                'class':'form-control',
            }),
            'justificativa' : forms.Textarea(attrs={
                'placeholder':'Justificativa',
                'class':'form-control',
                'cols': 5, 'rows': 5
            }),
            'objeto' : forms.TextInput(attrs={
                'placeholder':'Objeto',
                'class':'form-control',
            }),
            'contrato' : forms.CheckboxInput(attrs={'class': 'extclasses'}),
            'empenho' : forms.Select(attrs={
                'placeholder':'Tipo de Empenho',
                'class':'form-control',
            }),

        }


class ReqItemForm(forms.ModelForm):

    class Meta:
        model = ReqItem
        fields = ["id","item", "fk_requisicao","ordem", "quantidade","ed"]
        widgets = {
            'ordem' : forms.HiddenInput(),
            'item' : forms.Select(attrs={
                'placeholder':'Item',
                'class':'form-control',
            }),
            'quantidade' : forms.TextInput(attrs={
                'placeholder':'Quantidade',
                'class':'form-control',
            }),
            'ed' : forms.Select(attrs={
                'class':'form-control',
            }),
            'fk_requisicao' : forms.HiddenInput(),
        }


class CsvForm(forms.Form):
    options = (
                ('1','Sim'),
                ('2','Não'),
                )
    file  = forms.FileField()
    ordenar = forms.ChoiceField(choices=options)

apps/core/views.py
from django.shortcuts import render, get_object_or_404
from .models import Secretaria,Representante,Requisicao,Pregao,Beneficiaria,Item,EDespesa,ReqItem,Autorizacao,AutorizacaoReqItens
from .forms import RequisicaoForm, ReqItemForm, CsvForm
from .logic import ReportGenerator
from django.utils import formats
from django.http import HttpResponse, HttpResponseRedirect
from collections import defaultdict
from .extenso import converter_extenso
import csv, locale
locale.setlocale(locale.LC_ALL, '')

def index(request):
    template_name = 'index.html'
    rows = Requisicao.objects.all()
    context = dict(rows=rows)
    return render(request,template_name,context)


def beneficiarias(request):
    template_name = 'beneficiarias/index.html'
    rows = Beneficiaria.objects.all()
    context = dict(rows=rows)
    return render(request,template_name,context)


def secretarias(request):
    template_name = 'secretarias/index.html'
    rows = Secretaria.objects.all()
    context = dict(rows=rows)
    return render(request,template_name,context)


def beneficiaria_view(request,pk):
    template_name = 'beneficiarias/view.html'
    rows = get_object_or_404(Beneficiaria, pk=pk)
    context = dict(rows=rows)
    return render(request,template_name,context)


def requisicao_add(request):
    template_name = 'requisicao/add.html'
    form = RequisicaoForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = RequisicaoForm()
    context = dict(form=form)
    return render(request,template_name,context)


def requisicao_view(request,pk,pessoa):
    template_name = 'requisicao/view.html'
    requisicao = get_object_or_404(Requisicao,pk=pk)
    itens = ReqItem.objects.filter(fk_requisicao=pk).order_by('ed')
    erro = None
    eds = requisicao.ed.split(',')
    beneficiarias = Beneficiaria.objects.filter(
        CNPJ__in=itens.values_list('item__fk_beneficiaria', flat=True)
        )
    representante = Representante.objects.filter(
        cpf__in=itens.values_list('item__fk_representante', flat=True)
        )
    total = total_f(itens,i='id',q='quantidade',v='item__valor_unit')

    autorizacao = Autorizacao.objects.filter(fk_requisicao=pk)
    
    """Form Autorização """
    form = ReqItemForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/requisicao/{}/{}/'.format(pessoa,pk))
        else:
            erro = "#myModal"
    else:
        form = ReqItemForm(initial={'fk_requisicao': pk,'ordem':itens.count()+1})
        form.fields['item'].queryset = Item.objects.filter(fk_pregao=requisicao.fk_pregao,)
        form.fields['ed'].queryset = EDespesa.objects.filter(ed__in=eds)

    context = dict(
        requisicao=requisicao,
        ano=requisicao.get_ano_display(),
        data_pro=formats.date_format(requisicao.data_pro, "SHORT_DATE_FORMAT"),
        data_ass=formats.date_format(requisicao.assinatura, "SHORT_DATE_FORMAT"),
        erro=erro,
        form=form,
        itens=zip(itens,total['subtotal']),
        total=','.join(str(total['total']).split('.')),
        autorizacao=autorizacao,
        eds = [mask(str(ed),'ed') for ed in eds],
        extenso = converter_extenso(total['total']),
        )
    if pessoa == "F":
        context['beneficiarias'] = representante

    if pessoa == "J":
        context['beneficiarias'] = beneficiarias

    if request.GET.getlist('gerar'):
        if pessoa == "F":
            context['beneficiarias'] = representante
            creat_auth(requisicao,representante=representante)
            for item in itens:
                a = autorizacao.get(fk_representante=item.item.fk_representante)
                AutorizacaoReqItens.objects.get_or_create(fk_req_item=item,fk_autorizacao=a)
        if pessoa == "J":
            creat_auth(requisicao,beneficiarias=beneficiarias)
            for item in itens:
                a = autorizacao.get(fk_beneficiaria=item.item.fk_beneficiaria)
                AutorizacaoReqItens.objects.get_or_create(fk_req_item=item,fk_autorizacao=a)
        return HttpResponseRedirect('/requisicao/{}/{}/'.format(pessoa,pk))
    
    if request.GET.getlist('DownloadLib'):
        return ReportGenerator().liberacao(requisicao,context,itens)
    return render(request,template_name,context)


def auth_view(request,pk):
    template_name = 'autorizacao/view.html'
    autorizacao = get_object_or_404(Autorizacao, pk=pk)
    requisicao = get_object_or_404(Requisicao, pk=autorizacao.fk_requisicao_id)
    query = AutorizacaoReqItens.objects.filter(fk_autorizacao=autorizacao)
    eds = EDespesa.objects.filter(
        id__in = query.values_list('fk_req_item__ed', flat=False)
        )
    itens = ReqItem.objects.filter(
        item_id__in = query.values_list('fk_req_item__item__id', flat=False),fk_requisicao=requisicao
        )
    total = total_f(itens,i='id',q='quantidade',v='item__valor_unit')
    itemed = item_ed(eds,itens,total)
    pregao = requisicao.fk_pregao.n_pregao
    if len(requisicao.fk_pregao.n_pregao)<3:
        pregao = mask(str(requisicao.fk_pregao.n_pregao),'pregao')
    context = dict(
                rows = autorizacao,
                ano = requisicao.get_ano_display(),
                requisicao = requisicao.requisicao,
                fk_pregao = "{}/{}".format(pregao,requisicao.fk_pregao.get_ano_display()),
                secretaria = requisicao.secretaria,
                n_proc = requisicao.n_proc,
                objeto = str(requisicao.objeto).upper(),
                pa = requisicao.pa,
                eds = [mask(str(ed.ed),'ed') for ed in eds],
                meta = requisicao.meta,
                acao = requisicao.acao, 
                fonte = mask(str(requisicao.fonte),'fr'),
                justificativa = requisicao.justificativa,
                empenho = requisicao.empenho,
                itemed = itemed,
                total = total['total'],
                extenso = total['extenso'],
                assinatura = formats.date_format(requisicao.assinatura, "SHORT_DATE_FORMAT"),
                encerramento = formats.date_format(requisicao.vigencia, "SHORT_DATE_FORMAT"),
                dom_pregao = requisicao.fk_pregao.dom,
                data_pregao_dom = formats.date_format(requisicao.fk_pregao.data, "SHORT_DATE_FORMAT"),
                vigencia = ((requisicao.vigencia - requisicao.assinatura)//30),
                ass_extenso = requisicao.assinatura.strftime("%d de %B de %Y"),
                )

    context['ocorrencia'] = ["{ocorrencia.ocorrencia}: Retificado pelo Pregão Presencial Nº {pregao} do DOM {dom_pregao} de {data_pregao_dom} conforme Consta no DOM {ocorrencia.dom} de {ocorrencia_data}".format(
            ocorrencia = ocorrencia,
            pregao = context['fk_pregao'],
            dom_pregao = context['dom_pregao'],
            data_pregao_dom = context['data_pregao_dom'],
            ocorrencia_data = formats.date_format(ocorrencia.data, "SHORT_DATE_FORMAT")
        )
        for ocorrencia in requisicao.fk_pregao.ocorrencias.all()]

    if requisicao.pessoa == "J":
        beneficiaria = Beneficiaria.objects.get(
            CNPJ__in =query.values_list('fk_req_item__item__fk_beneficiaria', flat=True)
            )
        context['CNPJ'] = mask(str(beneficiaria.CNPJ),'cnpj')
        context['inscricao'] = mask(str(beneficiaria.inscricao),'inscricao')
        context['fone'] = mask(str(beneficiaria.phone),'fone')
        context['estado'] = beneficiaria.endereco.get_estado_display()
        context['beneficiaria'] = beneficiaria
        context['endereco'] = beneficiaria.endereco
        context['cep'] = mask(str(beneficiaria.endereco.cep),'cep')
        context['beneficiaria'] = beneficiaria

    if requisicao.pessoa == "F":
        representante = Representante.objects.get(
            cpf__in =query.values_list('fk_req_item__item__fk_representante', flat=True)
            )
        context['representante'] = representante
        context['cpf'] = mask(str(representante.cpf),'cpf')
        context['endereco'] = representante.endereco
        context['cep'] = mask(str(representante.endereco.cep),'cep')
        context['representante'] = representante
    if request.GET.getlist('download'):
        return ReportGenerator().autorizacao(context,autorizacao)

    print(context['vigencia'])

    if request.GET.getlist('contrato'):
        return ReportGenerator().contrato(context,autorizacao)
    return render(request,template_name,context)


def csv_add(request):
    template_name = "itens/add.html"
    return render(request, template_name, locals())



""" Métodos Total/Máscaras/ItemDespesas """

def creat_auth(instance,beneficiarias=None,representante=None):
    if beneficiarias:
        for b in beneficiarias:
            Autorizacao.objects.get_or_create(autorizacao=instance.aut,contrato=1,fk_requisicao=instance,fk_representante=None,fk_beneficiaria=b)
    else:
        for r in representante:
            Autorizacao.objects.get_or_create(autorizacao=instance.aut,contrato=1,fk_requisicao=instance,fk_representante=r,fk_beneficiaria=None)


def item_ed(eds,itens,total):
    defdic = defaultdict(list)
    itemed = dict()
    for ed in eds:
        for item,subtotal,valor_unit in zip(itens,total['subtotal'],total['valor_unit']):
            if ed == item.ed:
                defdic[mask(str(ed.ed),'ed'),].append([item,subtotal,valor_unit])

    for k, v in defdic.items():
        itemed[k]=v
    return itemed.items()


def total_f(instance,**v):
    grand = 0
    t = instance.values(v['q'],v['v'])
    subtotal = []
    valor_unit = []
    list_total = []
    for x in t:
        subtotal.append(locale.format('%.2f', (x['quantidade']*x['item__valor_unit']), True))
        valor_unit.append(locale.format('%.2f', x['item__valor_unit'], True))
        """locale.currency(1234567, grouping=True)"""

apps/core/templates/requisicao/add.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-12 panel-info">
	<form method="POST" action="" class="form-horizontal" role="form">{% csrf_token %}
		<div class="row">
			<div class="col-md-12 panel-info">
				<div class="content-box-large box-with-header">
							{{ form.errors }}
					<div>

					<div class="row">
						<div class="col-sm-2">
							<label class="control-label" for="select-2">Pregão</label>
							{{form.fk_pregao}}
						</div>
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Secretaria</label>
							{{form.secretaria}}
						</div>
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Nº do Processo</label>
							{{form.n_proc}}
						</div>
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Ano</label>
							{{form.ano}}
						</div>
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Nº Requisição</label>
							{{form.requisicao}}
						</div>
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Nº Autorização</label>
							{{form.aut}}
						</div>
					</div>
					<div class="row">
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Data do Processo</label>
							{{form.data_pro}}
						</div>
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Data da Assinatura</label>
							{{form.assinatura}}
						</div>
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Data de Encerramento</label>
							{{form.vigencia}}
						</div>
					</div>
					<div class="row">
		
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Projeto/Atividade</label>
							{{form.pa}}
						</div>

						<div class="col-sm-4">
							<label class="control-label" for="select-1">Elemento de Despesa</label>
							{{form.ed}}
						</div>

						<div class="col-sm-2">
							<label class="control-label" for="select-1">Meta</label>
							{{form.meta}}
						</div>

						<div class="col-sm-2">
							<label class="control-label" for="select-1">Ação</label>
							{{form.acao}}
						</div>

						<div class="col-sm-2">
							<label class="control-label" for="select-1">Fonte de Recursos</label>
							{{form.fonte}}
						</div>
					</div>
					<div class="row">
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Tipo de Empenho:</label>
							{{form.empenho}}
						</div>
						<div class="col-sm-2">
							<label class="control-label" for="select-1">Possui Contrato</label>
							{{form.contrato}}
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<label class="control-label" for="select-1">Objeto</label>
							{{form.objeto}}
						</div>
						<div class="col-sm-12">
							<label class="control-label" for="select-1">Justificativa</label>
							{{form.justificativa}}
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<input type="submit" class="btn btn-success" value="Salvar">
						</div>
					</div>
				</div>
				</div>
			</div>
		</div>
	</form>
</div>

{% endblock %}

apps/core/templates/requisicao/view.html
{% extends "base.html" %}
{% block content %}
<div class="content-box-large">
	<div class="panel-heading">
		<div class="panel-title">
			Processo: {{requisicao.n_proc}}/{{requisicao.get_ano_display}}
		</div>
		<div class="panel-options">
			<form action="" method="get">
	    		<button data-rel="collapse" class="btn btn-default btn-sm" name="DownloadLib" value="0"><i class="glyphicon glyphicon-download-alt"></i> Liberação
	    		</button>
				<a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
				<a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
				
			</form>
		</div>
	</div>
	<div class="panel-body">

	    <table class="table table-bordered">
	      <thead>
	        <tr>
	          <th>Secretaria</th>
	          <th>Data</th>
	          <th>Requisição/Ano</th>
	          <th>Autorização</th>
	          <th>Data do Processo</th>
	          <th>Data da Assinatura</th>
	        </tr>
	      </thead>
	      <tbody>
	        <tr class="odd gradeA">
	          <td>{{ requisicao.secretaria.sigla }}</td>
	          <td>{{ requisicao.data_pro }}</td>
	          <td>{{ requisicao.requisicao }}/{{ requisicao.get_ano_display }}</td>
	          <td>{{ requisicao.aut }}</td>
	          <td>{{ requisicao.data_pro }}</td>
	          <td>{{ requisicao.assinatura }}</td>
	        </tr>
	      </tbody>
	    </table>
	    <table class="table table-bordered">
	      <thead>
	        <tr>
	          <th>Projeto/Atividade</th>
	          <th>Elemento de Despesa</th>
	          <th>Meta</th>
	          <th>Ação</th>
	          <th>Fonte</th>
	        </tr>
	      </thead>
	      <tbody>
	        <tr class="odd gradeA">
	          <td>{{ requisicao.pa }}</td>
	          <td>
	          	{% for ed in eds %}
	          	{{ed}}
	          	{% endfor %}
	          </td>
	          <td>{{ requisicao.meta }}</td>
	          <td>{{ requisicao.acao }}</td>
	          <td>{{ requisicao.fonte }}</td>
	        </tr>
	      </tbody>
	    </table>
	    <table class="table table-bordered">
	      <thead>
	        <tr>
	          <th>Justificativa</th>
	        </tr>
	      </thead>
	      <tbody>
	        <tr class="odd gradeA">
	          <td>{{ requisicao.justificativa }}</td>
	        </tr>
	      </tbody>
	    </table>

	    <table class="table table-bordered">
	      <thead>
	        <tr>
	          <th>Ocorrências</th>
	        </tr>
	      </thead>
	      <tbody>
	        <tr class="odd gradeA">
	          <td>
	          	{% for row in requisicao.fk_pregao.ocorrencias.all %}
	          	<p>{{ row.ocorrencia }}: Retificado pelo Pregão Presencial Nº {{ requisicao.fk_pregao }} do DOM {{ requisicao.fk_pregao.dom }} de {{ requisicao.fk_pregao.data}} conforme Consta no DOM {{ row.dom }} de {{ row.data}}</p>
	          	{% endfor %}
	          </td>
	        </tr>
	      </tbody>
	    </table>

	    <div class="col-md-12 panel-info">
	    	{% if not autorizacao %}
	    	<form action="" method="GET">
	    		<div class="row">
	    			<button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal"><i class="glyphicon glyphicon-plus-sign"></i> Adicionar Iten</button>

	    			<button class="btn btn-default btn-sm" name="gerar" value="0">
	    				Gerar Autorizações
	    			</button>
	    		</div>
	    	</form>
	    	{% endif %}
	    </div>
	    <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Ordem</th>
                    <th>Descrição</th>
                    <th>Unidade</th>
                    <th>Quantidade</th>
                    <th>Valor unitário</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item,subtotal in itens %}
                <tr class="odd gradeA">
                    <td>{{ item.ordem }}</td>
                    <td>{{ item.item.desc }}</td>
                    <td>{{ item.item.tipo }}</td>
                    <td>{{ item.quantidade }}</td>
                    <td>R$ {{ item.item.valor_unit }}</td>
                    <td>R$ {{subtotal}}</td>
                </tr>
                {% endfor %}
            <tr>
                <td colspan="5">Total: {{extenso}}</td>
                <td>R$ {{total}}</td>
            </tr>
            </tbody>
        </table>

	    <table class="table table-bordered">

            <thead>
                <tr>
                    <th>Beneficiarias</th>
                    <th>Autorização</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
            	{% if not autorizacao %}
	                {% for beneficiaria in beneficiarias %}
	                <tr class="odd gradeA">
	                    <td>{{ beneficiaria }}</td>
	                </tr>
	                {% endfor %}
	            {% else %}
		            {% for beneficiaria in autorizacao %}
		            <tr class="odd gradeA">
		            	{% if beneficiaria.fk_beneficiaria %}
		                <td>{{ beneficiaria.fk_beneficiaria }}</td>
		            	{% elif beneficiaria.fk_representante %}
		                <td>{{ beneficiaria.fk_representante }}</td>
		                {% endif %}
		                <td>{{ beneficiaria.autorizacao }}</td>
	                	<td>
	                		<a href="{% url 'core:auth-view' pk=beneficiaria.id %}" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-eye-open"></i></a>
	                		<a href="{% url 'core:auth-view' pk=beneficiaria.id %}?download=0" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-download-alt"></i> Autorização </a>
	                		<a href="{% url 'core:auth-view' pk=beneficiaria.id %}?contrato=0" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-download-alt"></i> Contrato </a>
	                	</td>
		            </tr>
		            {% endfor %}

	            {% endif %}
            </tbody>
        </table>
	</div>

      <!-- Modal -->
    <form method="POST" action="">
      <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Adicionar Itens</h4>
            </div>
            <div class="modal-body">
            {% csrf_token %}
              {% for field in form %}
              <div class="form-group">
                  {{field}}
                  {{ field.errors }}
            </div>
              {% endfor %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <input class="btn btn-default" type="submit" value=" Salvar " />
            </div>
          </div>
        </div>
      </div>
    </form>
</div>
{% endblock %}